kind: pipeline
name: test

steps:
- name: test
  environment:
    utils_bool_test: true
    utils_int64_test: 55
    utils_uint64_test: 69
    utils_str_test: uwu
  image: golang
  commands:
  - go test -v
  when:
    branch:
    - master
